%% DESCRIPTION
%  Callback: exports coefficients in the format selected by the Structure dropdown.
%  Direct Form → b, a  |  SOS → sos matrix  |  State-Space → A, B, C, D
%% INPUTS
%  hobj  handle — source widget
%  evt   struct — event data
%% OUTPUTS
%  none

function cb_export_coeffs(hobj, evt)
  handles = guidata(hobj);

  STRUCT_KEYS = {'df', 'sos', 'ss'};
  structure   = STRUCT_KEYS{get(handles.dd_structure, 'Value')};

  % Build the data to export
  switch structure
    case 'df'
      export_df(handles);
    case 'sos'
      export_sos(handles);
    case 'ss'
      export_ss(handles);
  end
end

% ---- Direct Form (b / a) --------------------------------------------------
function export_df(handles)
  b = handles.b;
  a = handles.a;
  is_fir = (numel(a) == 1 && a(1) == 1);

  if is_fir
    choice = menu('Export — Direct Form (b/a)', ...
      'Export to workspace (b, a)', ...
      'Save as .mat file', ...
      'Save as .txt file', ...
      'Save as .h — CMSIS FIR (arm_fir_f32)', ...
      'Cancel');
  else
    choice = menu('Export — Direct Form (b/a)', ...
      'Export to workspace (b, a)', ...
      'Save as .mat file', ...
      'Save as .txt file', ...
      'Cancel');
  end

  switch choice
    case 1
      assignin('base', 'b', b);
      assignin('base', 'a', a);
      msgbox('Variables b and a exported to workspace.', 'Export', 'help');

    case 2
      [fname, fpath] = uiputfile('*.mat', 'Save coefficients as .mat');
      if fname ~= 0
        save(fullfile(fpath, fname), 'b', 'a');
      end

    case 3
      [fname, fpath] = uiputfile('*.txt', 'Save coefficients as .txt');
      if fname ~= 0
        fid = fopen(fullfile(fpath, fname), 'w');
        fprintf(fid, '# Filter: Direct Form\n');
        fprintf(fid, '# b (numerator) [1 x %d]\n', numel(b));
        fprintf(fid, '%.10g\n', b);
        fprintf(fid, '# a (denominator) [1 x %d]\n', numel(a));
        fprintf(fid, '%.10g\n', a);
        fclose(fid);
      end

    case 4   % only reachable for FIR
      [fname, fpath] = uiputfile('*.h', 'Save CMSIS FIR header');
      if fname ~= 0
        fid = fopen(fullfile(fpath, fname), 'w');
        write_fir_cmsis_header(fid, b, fname, handles.Fs);
        fclose(fid);
      end
  end
end

% ---- Second-Order Sections ------------------------------------------------
function export_sos(handles)
  try
    sos = tf2sos(handles.b, handles.a);
  catch e
    errordlg(['Could not convert to SOS: ' e.message], 'Export Error', 'modal');
    return;
  end

  choice = menu('Export — Second-Order Sections', ...
    'Export to workspace (sos)', ...
    'Save as .mat file', ...
    'Save as .h — CMSIS DF1  (arm_biquad_cascade_df1_f32)', ...
    'Save as .h — CMSIS DF2T (arm_biquad_cascade_df2T_f32)', ...
    'Cancel');

  switch choice
    case 1
      assignin('base', 'sos', sos);
      msgbox(sprintf('Variable sos exported to workspace (%d x 6 matrix).', size(sos,1)), ...
        'Export', 'help');

    case 2
      [fname, fpath] = uiputfile('*.mat', 'Save SOS as .mat');
      if fname ~= 0
        save(fullfile(fpath, fname), 'sos');
      end

    case 3
      [fname, fpath] = uiputfile('*.h', 'Save CMSIS header — DF1');
      if fname ~= 0
        fid = fopen(fullfile(fpath, fname), 'w');
        write_cmsis_header(fid, sos, 'df1', fname, handles.Fs);
        fclose(fid);
      end

    case 4
      [fname, fpath] = uiputfile('*.h', 'Save CMSIS header — DF2T');
      if fname ~= 0
        fid = fopen(fullfile(fpath, fname), 'w');
        write_cmsis_header(fid, sos, 'df2t', fname, handles.Fs);
        fclose(fid);
      end
  end
end

function write_fir_cmsis_header(fid, b, fname, Fs)
  num_taps = numel(b);

  guard = upper(strrep(fname, '.', '_'));
  guard = regexprep(guard, '[^A-Z0-9_]', '_');

  fprintf(fid, '#ifndef %s\n', guard);
  fprintf(fid, '#define %s\n\n', guard);

  fprintf(fid, '/*\n');
  fprintf(fid, ' * Auto-generated by Octave Filter Designer\n');
  fprintf(fid, ' * Structure  : FIR Direct Form (arm_fir_f32)\n');
  fprintf(fid, ' * Taps       : %d\n', num_taps);
  fprintf(fid, ' * Sample rate: %.6g Hz\n', Fs);
  fprintf(fid, ' *\n');
  fprintf(fid, ' * Usage:\n');
  fprintf(fid, ' *   #include "%s"\n', fname);
  fprintf(fid, ' *   filter_init();\n');
  fprintf(fid, ' *   filter_process(pSrc, pDst, blockSize);\n');
  fprintf(fid, ' */\n\n');

  fprintf(fid, '#include "arm_math.h"\n\n');
  fprintf(fid, '#define FILTER_NUM_TAPS %d\n\n', num_taps);

  % Coefficient array (CMSIS FIR expects coefficients in reverse order)
  fprintf(fid, '/* Coefficients in reverse order as required by arm_fir_f32 */\n');
  fprintf(fid, 'static float32_t filter_coeffs[FILTER_NUM_TAPS] = {\n');
  b_rev = b(end:-1:1);
  for k = 1:num_taps
    sep = '';
    if k < num_taps; sep = ','; end
    fprintf(fid, '    %.10gf%s\n', b_rev(k), sep);
  end
  fprintf(fid, '};\n\n');

  % State buffer — must be blockSize + numTaps - 1 words; declare max common size
  fprintf(fid, '/* State buffer: blockSize + FILTER_NUM_TAPS - 1 words\n');
  fprintf(fid, '   Adjust FILTER_BLOCK_SIZE to match your DMA block size. */\n');
  fprintf(fid, '#ifndef FILTER_BLOCK_SIZE\n');
  fprintf(fid, '#define FILTER_BLOCK_SIZE 64\n');
  fprintf(fid, '#endif\n\n');
  fprintf(fid, 'static float32_t filter_state[FILTER_BLOCK_SIZE + FILTER_NUM_TAPS - 1];\n\n');

  fprintf(fid, 'static arm_fir_instance_f32 filter_instance;\n\n');

  % Inline init
  fprintf(fid, 'static inline void filter_init(void) {\n');
  fprintf(fid, '    arm_fir_init_f32(\n');
  fprintf(fid, '        &filter_instance, FILTER_NUM_TAPS,\n');
  fprintf(fid, '        filter_coeffs, filter_state, FILTER_BLOCK_SIZE);\n');
  fprintf(fid, '}\n\n');

  % Inline process
  fprintf(fid, 'static inline void filter_process(\n');
  fprintf(fid, '        float32_t *pSrc, float32_t *pDst, uint32_t blockSize) {\n');
  fprintf(fid, '    arm_fir_f32(&filter_instance, pSrc, pDst, blockSize);\n');
  fprintf(fid, '}\n\n');

  fprintf(fid, '#endif /* %s */\n', guard);
end

function write_cmsis_header(fid, sos, variant, fname, Fs)
  n_stages = size(sos, 1);

  if strcmp(variant, 'df1')
    init_fn   = 'arm_biquad_cascade_df1_init_f32';
    filter_fn = 'arm_biquad_cascade_df1_f32';
    inst_type = 'arm_biquad_casd_df1_inst_f32';
    state_per = 4;
    variant_str = 'Direct Form I';
  else
    init_fn   = 'arm_biquad_cascade_df2T_init_f32';
    filter_fn = 'arm_biquad_cascade_df2T_f32';
    inst_type = 'arm_biquad_cascade_df2T_instance_f32';
    state_per = 2;
    variant_str = 'Direct Form II Transposed';
  end

  % Include guard from filename (strip extension, uppercase)
  guard = upper(strrep(fname, '.', '_'));
  guard = regexprep(guard, '[^A-Z0-9_]', '_');

  fprintf(fid, '#ifndef %s\n', guard);
  fprintf(fid, '#define %s\n\n', guard);

  fprintf(fid, '/*\n');
  fprintf(fid, ' * Auto-generated by Octave Filter Designer\n');
  fprintf(fid, ' * Structure : Biquad Cascade — %s\n', variant_str);
  fprintf(fid, ' * Stages    : %d\n', n_stages);
  fprintf(fid, ' * Sample rate: %.6g Hz\n', Fs);
  fprintf(fid, ' *\n');
  fprintf(fid, ' * Coefficient order per stage: b0, b1, b2, -a1, -a2  (a0 normalised to 1)\n');
  fprintf(fid, ' * State buffer size          : %d words (%d per stage)\n', ...
    state_per * n_stages, state_per);
  fprintf(fid, ' *\n');
  fprintf(fid, ' * Usage:\n');
  fprintf(fid, ' *   #include "%s"\n', fname);
  fprintf(fid, ' *   filter_init();\n');
  fprintf(fid, ' *   filter_process(pSrc, pDst, blockSize);\n');
  fprintf(fid, ' */\n\n');

  fprintf(fid, '#include "arm_math.h"\n\n');
  fprintf(fid, '#define FILTER_NUM_STAGES %d\n\n', n_stages);

  % Reference SOS matrix as a comment
  fprintf(fid, '/* Reference SOS matrix — columns: b0 b1 b2 a0 a1 a2\n');
  for k = 1:n_stages
    fprintf(fid, '   stage %d: %.8g  %.8g  %.8g  %.8g  %.8g  %.8g\n', ...
      k, sos(k,1), sos(k,2), sos(k,3), sos(k,4), sos(k,5), sos(k,6));
  end
  fprintf(fid, '*/\n\n');

  % Coefficient array
  fprintf(fid, 'static float32_t filter_coeffs[5 * FILTER_NUM_STAGES] = {\n');
  for k = 1:n_stages
    b0 =  sos(k,1) / sos(k,4);
    b1 =  sos(k,2) / sos(k,4);
    b2 =  sos(k,3) / sos(k,4);
    a1 = -sos(k,5) / sos(k,4);
    a2 = -sos(k,6) / sos(k,4);
    sep = '';
    if k < n_stages; sep = ','; end
    fprintf(fid, '    /* stage %d */ %.10gf, %.10gf, %.10gf, %.10gf, %.10gf%s\n', ...
      k, b0, b1, b2, a1, a2, sep);
  end
  fprintf(fid, '};\n\n');

  % State buffer and instance (zero-initialised by static)
  fprintf(fid, 'static float32_t filter_state[%d * FILTER_NUM_STAGES];\n\n', state_per);
  fprintf(fid, 'static %s filter_instance;\n\n', inst_type);

  % Inline init function
  fprintf(fid, 'static inline void filter_init(void) {\n');
  fprintf(fid, '    %s(\n', init_fn);
  fprintf(fid, '        &filter_instance, FILTER_NUM_STAGES,\n');
  fprintf(fid, '        filter_coeffs, filter_state);\n');
  fprintf(fid, '}\n\n');

  % Inline process function
  fprintf(fid, 'static inline void filter_process(\n');
  fprintf(fid, '        float32_t *pSrc, float32_t *pDst, uint32_t blockSize) {\n');
  fprintf(fid, '    %s(\n', filter_fn);
  fprintf(fid, '        &filter_instance, pSrc, pDst, blockSize);\n');
  fprintf(fid, '}\n\n');

  fprintf(fid, '#endif /* %s */\n', guard);
end

% ---- State-Space ----------------------------------------------------------
function export_ss(handles)
  try
    [A, B, C, D] = tf2ss(handles.b, handles.a);
  catch e
    errordlg(['Could not convert to State-Space: ' e.message], 'Export Error', 'modal');
    return;
  end

  choice = menu('Export — State-Space (A, B, C, D)', ...
    'Export to workspace (A, B, C, D)', ...
    'Save as .mat file', ...
    'Save as .txt file', ...
    'Cancel');

  switch choice
    case 1
      assignin('base', 'A', A);
      assignin('base', 'B', B);
      assignin('base', 'C', C);
      assignin('base', 'D', D);
      msgbox('Variables A, B, C, D exported to workspace.', 'Export', 'help');

    case 2
      [fname, fpath] = uiputfile('*.mat', 'Save State-Space as .mat');
      if fname ~= 0
        save(fullfile(fpath, fname), 'A', 'B', 'C', 'D');
      end

    case 3
      [fname, fpath] = uiputfile('*.txt', 'Save State-Space as .txt');
      if fname ~= 0
        fid = fopen(fullfile(fpath, fname), 'w');
        fprintf(fid, '# Filter: State-Space\n\n');
        write_matrix(fid, 'A', A);
        write_matrix(fid, 'B', B);
        write_matrix(fid, 'C', C);
        write_matrix(fid, 'D', D);
        fclose(fid);
      end
  end
end

function write_matrix(fid, name, M)
  [r, c] = size(M);
  fprintf(fid, '# %s [%d x %d]\n', name, r, c);
  for i = 1:r
    fprintf(fid, '  ');
    fprintf(fid, '%.10g  ', M(i,:));
    fprintf(fid, '\n');
  end
  fprintf(fid, '\n');
end
