%% DESCRIPTION
%  Creates the left control panel: filter type, design method, and parameters.
%% INPUTS
%  parent   handle — parent container
%% OUTPUTS
%  handles  struct — widget handles for this panel

function handles = build_control_panel(parent)
  handles = struct();

  % --- Filter type radios ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.92 0.40 0.04], ...
    'String', 'Filter Type:', 'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold');

  handles.rb_fir = uicontrol('Parent', parent, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.87 0.40 0.04], ...
    'String', 'FIR', 'Value', 1, 'Tag', 'rb_fir');

  handles.rb_iir = uicontrol('Parent', parent, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.50 0.87 0.40 0.04], ...
    'String', 'IIR', 'Value', 0, 'Tag', 'rb_iir');

  % --- Method dropdown ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.81 0.40 0.04], ...
    'String', 'Method:', 'HorizontalAlignment', 'left');

  handles.dd_method = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.77 0.88 0.04], ...
    'String', {'Window', 'Least-Squares', 'Parks-McClellan'}, ...
    'Value', 1, 'Tag', 'dd_method');

  % --- Band type dropdown ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.71 0.40 0.04], ...
    'String', 'Band:', 'HorizontalAlignment', 'left');

  handles.dd_band = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.67 0.88 0.04], ...
    'String', {'Lowpass', 'Highpass', 'Bandpass', 'Bandstop'}, ...
    'Value', 1, 'Tag', 'dd_band');

  % --- Filter order ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.61 0.40 0.04], ...
    'String', 'Order:', 'HorizontalAlignment', 'left');

  handles.ed_order = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.61 0.43 0.04], ...
    'String', '40', 'Tag', 'ed_order');

  % --- Cutoff frequency in Hz ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.55 0.40 0.04], ...
    'String', 'Cutoff (Hz):', 'HorizontalAlignment', 'left');

  handles.ed_wn = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.55 0.43 0.04], ...
    'String', '1000', 'Tag', 'ed_wn');

  % --- Sample rate Fs ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.49 0.40 0.04], ...
    'String', 'Fs (Hz):', 'HorizontalAlignment', 'left');

  handles.ed_fs = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.49 0.43 0.04], ...
    'String', '8000', 'Tag', 'ed_fs');

  % --- Window type (FIR only) ---
  handles.lbl_window = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.43 0.40 0.04], ...
    'String', 'Window:', 'HorizontalAlignment', 'left', ...
    'Tag', 'lbl_window');

  handles.dd_window = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.39 0.88 0.04], ...
    'String', {'Hamming', 'Hann', 'Blackman', 'Kaiser', 'Rectangular'}, ...
    'Value', 1, 'Tag', 'dd_window');

  % --- Kaiser beta (visible only when kaiser selected) ---
  handles.lbl_kaiser = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.33 0.40 0.04], ...
    'String', 'Kaiser β:', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_kaiser');

  handles.ed_kaiser = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.33 0.43 0.04], ...
    'String', '5', 'Visible', 'off', 'Tag', 'ed_kaiser');

  % --- Passband ripple Rp (IIR cheby1 / ellip) ---
  handles.lbl_rp = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.33 0.40 0.04], ...
    'String', 'Rp (dB):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_rp');

  handles.ed_rp = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.33 0.43 0.04], ...
    'String', '1', 'Visible', 'off', 'Tag', 'ed_rp');

  % --- Stopband ripple Rs (IIR cheby2 / ellip) ---
  handles.lbl_rs = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.27 0.40 0.04], ...
    'String', 'Rs (dB):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_rs');

  handles.ed_rs = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.27 0.43 0.04], ...
    'String', '40', 'Visible', 'off', 'Tag', 'ed_rs');

  % --- Stability warning label ---
  handles.lbl_stability = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.20 0.88 0.04], ...
    'String', 'WARNING: Unstable filter', ...
    'ForegroundColor', [0.8 0 0], ...
    'Visible', 'off', 'Tag', 'lbl_stability');

  % --- Action buttons ---
  handles.btn_design = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.05 0.10 0.88 0.06], ...
    'String', 'Design Filter', 'FontWeight', 'bold', 'Tag', 'btn_design');

  handles.btn_reset = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.05 0.03 0.40 0.05], ...
    'String', 'Reset', 'Tag', 'btn_reset');

  handles.btn_export = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.52 0.03 0.40 0.05], ...
    'String', 'Export', 'Tag', 'btn_export');
end
