%% DESCRIPTION
%  Creates the right panel: a row of plot-selector buttons and one large
%  display area that shows the active plot or the coefficient table.
%% INPUTS
%  parent   handle — parent container
%% OUTPUTS
%  handles  struct — ax_main, tbl_coeffs, btns_plot

function handles = build_plot_panel(parent)
  handles = struct();

  PLOT_KEYS   = {'magnitude','phase','phase_delay','group_delay', ...
                 'polezero','impulse','coefficients'};
  PLOT_LABELS = {'Magnitude','Phase','Ph. Delay','Grp. Delay', ...
                 'Pole-Zero','Impulse','Coefficients'};
  N = numel(PLOT_KEYS);

  % ---- Button strip across the top ----------------------------------------
  btn_w = (1 - 0.02) / N;     % fill panel width with tiny left margin
  btn_y = 0.93;
  btn_h = 0.06;

  btn_handles = zeros(1, N);
  for i = 1:N
    btn_handles(i) = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
      'Units', 'normalized', ...
      'Position', [0.01 + (i-1)*btn_w,  btn_y,  btn_w - 0.005,  btn_h], ...
      'String', PLOT_LABELS{i}, ...
      'Tag', PLOT_KEYS{i}, ...
      'FontSize', 8, ...
      'BackgroundColor', [0.94 0.94 0.94]);
  end

  % Default active button: Magnitude
  set(btn_handles(1), 'BackgroundColor', [0.30 0.60 1.00]);
  set(btn_handles(1), 'ForegroundColor', [1 1 1]);

  handles.btns_plot = btn_handles;

  % ---- Phase wrap toggle (only visible when Phase plot is active) ----------
  handles.btn_phase_wrap = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.80 0.895 0.18 0.030], ...
    'String', 'Wrapped', ...
    'FontSize', 8, ...
    'BackgroundColor', [0.30 0.60 1.00], ...
    'ForegroundColor', [1 1 1], ...
    'Visible', 'off');

  % ---- Main display area ---------------------------------------------------
  % axes Position is the inner plot box; labels render outside it, so pull
  % the box inward enough that ylabel+ticks (left) and xlabel+ticks (bottom)
  % are not clipped by the panel boundary.
  axes_pos = [0.11 0.11 0.84 0.77];
  tbl_pos  = [0.01 0.02 0.98 0.89];

  handles.ax_main = axes('Parent', parent, ...
    'Units', 'normalized', 'Position', axes_pos);
  grid(handles.ax_main, 'on');

  handles.tbl_coeffs = uitable('Parent', parent, ...
    'Units', 'normalized', 'Position', tbl_pos, ...
    'ColumnName', {'Index', 'b (num)', 'a (den)'}, ...
    'ColumnWidth', {50, 120, 120}, ...
    'RowName', {}, ...
    'Data', {}, ...
    'Visible', 'off');
end
