%% DESCRIPTION
%  Creates the left control panel: filter type, design method, and parameters.
%  Parameters are split into Frequency and Magnitude sections.
%% INPUTS
%  parent   handle — parent container
%% OUTPUTS
%  handles  struct — widget handles for this panel

function handles = build_control_panel(parent)
  handles = struct();

  % --- Filter type ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.92 0.40 0.03], ...
    'String', 'Filter Type:', 'HorizontalAlignment', 'left', 'FontWeight', 'bold');

  handles.rb_fir = uicontrol('Parent', parent, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.88 0.40 0.04], ...
    'String', 'FIR', 'Value', 1, 'Tag', 'rb_fir');

  handles.rb_iir = uicontrol('Parent', parent, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.50 0.88 0.40 0.04], ...
    'String', 'IIR', 'Value', 0, 'Tag', 'rb_iir');

  % --- Method ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.83 0.40 0.03], ...
    'String', 'Method:', 'HorizontalAlignment', 'left');

  handles.dd_method = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.79 0.88 0.04], ...
    'String', {'Window', 'Least-Squares', 'Parks-McClellan'}, ...
    'Value', 1, 'Tag', 'dd_method');

  % --- Band type ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.74 0.40 0.03], ...
    'String', 'Band:', 'HorizontalAlignment', 'left');

  handles.dd_band = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.70 0.88 0.04], ...
    'String', {'Lowpass', 'Highpass', 'Bandpass', 'Bandstop'}, ...
    'Value', 1, 'Tag', 'dd_band');

  % --- Filter order ---
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.65 0.40 0.04], ...
    'String', 'Order:', 'HorizontalAlignment', 'left');

  handles.ed_order = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.65 0.43 0.04], ...
    'String', '40', 'Tag', 'ed_order');

  % =========================================================
  % FREQUENCY PARAMETERS SECTION
  % =========================================================
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.61 0.88 0.03], ...
    'String', '--- Frequency Parameters ---', ...
    'HorizontalAlignment', 'center', 'FontWeight', 'bold');

  % Freq unit (label + dropdown on same row)
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.57 0.38 0.04], ...
    'String', 'Freq Unit:', 'HorizontalAlignment', 'left');

  handles.dd_freq_unit = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.44 0.57 0.49 0.04], ...
    'String', {'Hz', 'kHz', 'MHz', 'GHz', 'Normalized'}, ...
    'Value', 1, 'Tag', 'dd_freq_unit');

  % Fs
  handles.lbl_fs = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.53 0.40 0.04], ...
    'String', 'Fs (Hz):', 'HorizontalAlignment', 'left', 'Tag', 'lbl_fs');

  handles.ed_fs = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.53 0.43 0.04], ...
    'String', '8000', 'Tag', 'ed_fs');

  % Generic cutoff — window / IIR methods
  handles.lbl_wn = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.49 0.40 0.04], ...
    'String', 'Cutoff (Hz):', 'HorizontalAlignment', 'left', 'Tag', 'lbl_wn');

  handles.ed_wn = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.49 0.43 0.04], ...
    'String', '1000', 'Tag', 'ed_wn');

  % LS/PM: first band-edge (Fpass for lowpass/bandstop; Fstop for highpass/bandpass)
  handles.lbl_fpass = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.49 0.40 0.04], ...
    'String', 'Fpass (Hz):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_fpass');

  handles.ed_fpass = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.49 0.43 0.04], ...
    'String', '900', 'Visible', 'off', 'Tag', 'ed_fpass');

  % LS/PM: second band-edge
  handles.lbl_fstop = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.45 0.40 0.04], ...
    'String', 'Fstop (Hz):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_fstop');

  handles.ed_fstop = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.45 0.43 0.04], ...
    'String', '1100', 'Visible', 'off', 'Tag', 'ed_fstop');

  % LS/PM: third band-edge (2-band only)
  handles.lbl_fpass2 = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.41 0.40 0.04], ...
    'String', 'Fpass2 (Hz):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_fpass2');

  handles.ed_fpass2 = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.41 0.43 0.04], ...
    'String', '2000', 'Visible', 'off', 'Tag', 'ed_fpass2');

  % LS/PM: fourth band-edge (2-band only)
  handles.lbl_fstop2 = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.37 0.40 0.04], ...
    'String', 'Fstop2 (Hz):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_fstop2');

  handles.ed_fstop2 = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.37 0.43 0.04], ...
    'String', '2200', 'Visible', 'off', 'Tag', 'ed_fstop2');

  % =========================================================
  % MAGNITUDE PARAMETERS SECTION
  % =========================================================
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.33 0.88 0.03], ...
    'String', '--- Magnitude Parameters ---', ...
    'HorizontalAlignment', 'center', 'FontWeight', 'bold');

  % Window type label — FIR window method only
  handles.lbl_window = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.29 0.88 0.04], ...
    'String', 'Window:', 'HorizontalAlignment', 'left', 'Tag', 'lbl_window');

  % Window dropdown (full-width, row below label)
  handles.dd_window = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.05 0.25 0.88 0.04], ...
    'String', {'Hamming', 'Hann', 'Blackman', 'Kaiser', 'Rectangular'}, ...
    'Value', 1, 'Tag', 'dd_window');

  % Kaiser beta
  handles.lbl_kaiser = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.21 0.40 0.04], ...
    'String', 'Kaiser β:', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_kaiser');

  handles.ed_kaiser = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.21 0.43 0.04], ...
    'String', '5', 'Visible', 'off', 'Tag', 'ed_kaiser');

  % Rp — cheby1 / ellip  (same row as lbl_window — mutually exclusive)
  handles.lbl_rp = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.29 0.40 0.04], ...
    'String', 'Rp (dB):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_rp');

  handles.ed_rp = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.29 0.43 0.04], ...
    'String', '1', 'Visible', 'off', 'Tag', 'ed_rp');

  % Rs — cheby2 / ellip  (same row as dd_window — mutually exclusive)
  handles.lbl_rs = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.25 0.40 0.04], ...
    'String', 'Rs (dB):', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_rs');

  handles.ed_rs = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.25 0.43 0.04], ...
    'String', '40', 'Visible', 'off', 'Tag', 'ed_rs');

  % Wpass — LS / PM  (same row as lbl_window — mutually exclusive)
  handles.lbl_wpass = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.29 0.40 0.04], ...
    'String', 'Wpass:', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_wpass');

  handles.ed_wpass = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.29 0.43 0.04], ...
    'String', '1', 'Visible', 'off', 'Tag', 'ed_wpass');

  % Wstop — LS / PM  (same row as dd_window — mutually exclusive)
  handles.lbl_wstop = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.25 0.40 0.04], ...
    'String', 'Wstop:', 'HorizontalAlignment', 'left', ...
    'Visible', 'off', 'Tag', 'lbl_wstop');

  handles.ed_wstop = uicontrol('Parent', parent, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.50 0.25 0.43 0.04], ...
    'String', '1', 'Visible', 'off', 'Tag', 'ed_wstop');

  % --- Stability warning ---
  handles.lbl_stability = uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.05 0.19 0.88 0.04], ...
    'String', 'WARNING: Unstable filter', ...
    'ForegroundColor', [0.8 0 0], ...
    'Visible', 'off', 'Tag', 'lbl_stability');

  % --- Action buttons ---
  handles.btn_design = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.05 0.14 0.88 0.04], ...
    'String', 'Design Filter', 'FontWeight', 'bold', 'Tag', 'btn_design');

  handles.btn_import = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.05 0.09 0.88 0.04], ...
    'String', 'Import / Edit Coefficients', 'Tag', 'btn_import');

  handles.btn_reset = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.05 0.04 0.40 0.04], ...
    'String', 'Reset', 'Tag', 'btn_reset');

  handles.btn_export = uicontrol('Parent', parent, 'Style', 'pushbutton', ...
    'Units', 'normalized', 'Position', [0.52 0.04 0.40 0.04], ...
    'String', 'Export', 'Tag', 'btn_export');
end
