%% DESCRIPTION
%  Creates the right panel: three selectable plot quadrants and a fixed
%  coefficient table in the bottom-right.
%% INPUTS
%  parent   handle — parent container
%% OUTPUTS
%  handles  struct — axes (ax_q1/q2/q3), dropdowns (dd_q1/q2/q3), tbl_coeffs

function handles = build_plot_panel(parent)
  handles = struct();
  TITLE_SIZE   = 11;
  PLOT_STRINGS = {'Magnitude', 'Phase', 'Group Delay', 'Pole-Zero', 'Impulse'};

  % ---- Top-left (Q1) — default: Magnitude --------------------------------
  handles.dd_q1 = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.03 0.94 0.44 0.04], ...
    'String', PLOT_STRINGS, 'Value', 1, 'Tag', 'dd_q1');

  handles.ax_q1 = axes('Parent', parent, ...
    'Units', 'normalized', 'Position', [0.03 0.51 0.44 0.42]);
  grid(handles.ax_q1, 'on');

  % ---- Top-right (Q2) — default: Pole-Zero --------------------------------
  handles.dd_q2 = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.53 0.94 0.44 0.04], ...
    'String', PLOT_STRINGS, 'Value', 4, 'Tag', 'dd_q2');

  handles.ax_q2 = axes('Parent', parent, ...
    'Units', 'normalized', 'Position', [0.53 0.51 0.44 0.42]);
  grid(handles.ax_q2, 'on');

  % ---- Bottom-left (Q3) — default: Impulse --------------------------------
  handles.dd_q3 = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'Units', 'normalized', 'Position', [0.03 0.46 0.44 0.04], ...
    'String', PLOT_STRINGS, 'Value', 5, 'Tag', 'dd_q3');

  handles.ax_q3 = axes('Parent', parent, ...
    'Units', 'normalized', 'Position', [0.03 0.04 0.44 0.41]);
  grid(handles.ax_q3, 'on');

  % ---- Bottom-right — fixed: Coefficients ---------------------------------
  uicontrol('Parent', parent, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.53 0.46 0.44 0.04], ...
    'String', 'Coefficients', ...
    'FontWeight', 'bold', 'FontSize', TITLE_SIZE, ...
    'HorizontalAlignment', 'center');

  handles.tbl_coeffs = uitable('Parent', parent, ...
    'Units', 'normalized', 'Position', [0.53 0.04 0.44 0.41], ...
    'ColumnName', {'Index', 'b (num)', 'a (den)'}, ...
    'ColumnWidth', {40, 90, 90}, ...
    'RowName', {}, ...
    'Data', {});
end
